version: '3.7'


services:
  db: 
    container_name: moviestore-app
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
    - "3309:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "movie"
      MYSQL_USER: "movie_user"
      MYSQL_PASSWORD: "secret"
    volumes:
    - mysql_data:/var/lib/mysql 
    command: --default-authentication-plugin=my_native_password
  api:
    container_name: "movie_api"
    build:
      context: .
      dockerfile: api.Dockerfile

    ports:
    - "8080:8080"
    depends_on:
      - db 
    volumes:
    - .:/app/
networks:
  default:
volumes:
  mysql_data: 

